---

version: "2.4"
services:
  storage01:
    image: nspccdev/neofs-storage-testnet:0.27.7
    container_name: neofs-testnet
    env_file: node_config.env
    network_mode: host
    restart: always
    volumes:
      - neofs_storage:/storage
      - <NEOFS_NODE_KEY>:/node.key
    stop_signal: SIGINT

volumes:
  neofs_storage:
