FROM golang:1.22 as builder
ARG BUILD=now
ARG VERSION=dev
ARG REPO=repository
WORKDIR /src
COPY . /src

RUN make bin/epicchain-node

# Executable image
FROM scratch

WORKDIR /

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /src/bin/epicchain-node /bin/epicchain-node
COPY --from=builder /src/config/testnet/config.yml /config.yml

CMD ["epicchain-node", "--config", "/config.yml"]
