name: Run automated system tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - support/**
    types: [opened, synchronize]
    paths-ignore:
      - '**/*.md'
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      neofs_node_ref:
        description: 'epicchain-node ref. Default: master/PR. Examples: v0.36.0, 8fdcc6d7e798e6511be8806b81894622e72d7fdc, branch_name'
        required: false
        default: ''
      neofs_testcases_ref:
        description: 'neofs-testcases ref. Default: master. Examples: v0.36.0, 8fdcc6d7e798e6511be8806b81894622e72d7fdc, branch_name'
        required: false
        default: 'master'
      run_all_tests:
        description: 'Force running all tests, by default PRs trigger sanity test runs only'
        required: false
        default: 'false'

permissions: write-all

env:
  ALLURE_RESULTS_DIR: ${{ github.workspace }}/allure-results

jobs:
  run_system_tests:
    runs-on: ${{ matrix.os.runner }}
    strategy:
      fail-fast: false
      matrix:
        os: [{runner: 'ubuntu-latest', binary: 'linux-amd64'}, {runner: 'macos-14', binary: 'darwin-arm64'}]
    timeout-minutes: 500
    steps:
      - name: Checkout neofs-testcases repository
        uses: actions/checkout@v4
        with:
          repository: nspcc-dev/neofs-testcases
          ref: ${{ github.event.inputs.neofs_testcases_ref }}
          path: neofs-testcases

      - name: Checkout neofs-s3-gw repository
        uses: actions/checkout@v4
        with:
          repository: nspcc-dev/neofs-s3-gw
          ref: v0.30.0
          path: neofs-s3-gw

      - name: Checkout neofs-rest-gw repository
        uses: actions/checkout@v4
        with:
          repository: nspcc-dev/neofs-rest-gw
          ref: master
          path: neofs-rest-gw

      - name: Checkout epicchain-node repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.neofs_node_ref }}
          path: epicchain-node

#################################################################
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version: '1.22'
      - run: go version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python --version

# Hashlib uses OpenSSL for ripemd160 and apparently OpenSSL disabled some older crypto algos around version 3.0
# in November 2021. All the functions are still there but require manual enabling.
# See https://github.com/openssl/openssl/issues/16994
# But we use ripemd160 for tests.
# For ripemd160 to be supported, we need the openssl configuration file to contain the following lines:
# openssl_conf = openssl_init
#
# [openssl_init]
# providers = provider_sect
#
# [provider_sect]
# default = default_sect
# legacy = legacy_sect
#
# [default_sect]
# activate = 1
#
# [legacy_sect]
# activate = 1
      - name: Fix OpenSSL ripemd160
        run: |
          sudo python ./tools/src/openssl_config_fix.py
        working-directory: neofs-testcases

################################################################
      - name: Build epicchain-node
        timeout-minutes: 5
        run: |
          make all
          echo "$(pwd)/bin" >> $GITHUB_PATH
        working-directory: epicchain-node

      - name: Build neofs-s3-gw
        timeout-minutes: 5
        run: |
          make all
          echo "$(pwd)/bin" >> $GITHUB_PATH
        working-directory: neofs-s3-gw

      - name: Build neofs-rest-gw
        timeout-minutes: 5
        run: |
          make all
          echo "$(pwd)/bin" >> $GITHUB_PATH
        working-directory: neofs-rest-gw

################################################################

      - name: Download latest stable neo-go
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          repo: 'nspcc-dev/neo-go'
          version: 'tags/v0.104.0'
          file: 'neo-go-${{ matrix.os.binary }}'
          target: 'neofs-testcases/neo-go'

      - name: Copy built binaries
        timeout-minutes: 30
        run: |
          ls -la ../epicchain-node/bin
          cp ../neofs-s3-gw/bin/neofs-s3-gw .
          cp ../neofs-s3-gw/bin/neofs-s3-authmate .
          cp ../neofs-rest-gw/bin/neofs-rest-gw .
          cp ../epicchain-node/bin/epicchain-adm .
          cp ../epicchain-node/bin/epicchain-cli .
          cp ../epicchain-node/bin/epicchain-ir .
          cp ../epicchain-node/bin/epicchain-lens .
          cp ../epicchain-node/bin/epicchain-node .
        working-directory: neofs-testcases

      - name: Chmod binaries
        run: |
          sudo chmod a+x epicchain-cli
          sudo chmod a+x epicchain-adm
          sudo chmod a+x epicchain-ir
          sudo chmod a+x epicchain-lens
          sudo chmod a+x epicchain-node
          sudo chmod a+x neofs-rest-gw
          sudo chmod a+x neo-go
          sudo chmod a+x neofs-s3-authmate
          sudo chmod a+x neofs-s3-gw
        working-directory: neofs-testcases

      - name: Prepare venv
        id: prepare_venv
        timeout-minutes: 30
        run: |
          make venv.pytest
          echo "$(pwd)" >> $GITHUB_PATH
        working-directory: neofs-testcases

################################################################
      - name: Log environment
        run: |
          echo "Check free space"
          df -h
          echo "=========================================="

          echo "Check neo-go version"
          neo-go --version
          echo "=========================================="

          echo "Check neofs-s3-authmate version"
          neofs-s3-authmate --version
          echo "=========================================="

          echo "Check neofs-s3-gw version"
          echo "=========================================="
          neofs-s3-gw --version
          echo "=========================================="

          echo "Check epicchain-adm version"
          epicchain-adm --version
          echo "=========================================="

          echo "Check epicchain-ir version"
          epicchain-ir --version
          echo "=========================================="

          echo "Check epicchain-lens version"
          epicchain-lens --version
          echo "=========================================="

          echo "Check epicchain-cli version"
          epicchain-cli --version
          echo "=========================================="

          echo "Check bin dir"
          ls -lah "${GITHUB_WORKSPACE}/epicchain-node/bin"
          echo "=========================================="
        working-directory: neofs-testcases

################################################################
      - name: Run sanity tests
        timeout-minutes: 120
        if: ${{ !github.event.inputs.run_all_tests && github.event_name == 'pull_request' }}
        env:
          ALLURE_RESULTS_DIR: ${{ env.ALLURE_RESULTS_DIR }}
        run: |
          source venv.pytest/bin/activate && pytest --show-capture=no -m "sanity" --alluredir=${GITHUB_WORKSPACE}/allure-results pytest_tests/tests
        working-directory: neofs-testcases

      - name: Run all tests
        timeout-minutes: 480
        if: ${{ github.event.inputs.run_all_tests || github.event_name != 'pull_request' }}
        env:
          ALLURE_RESULTS_DIR: ${{ env.ALLURE_RESULTS_DIR }}
        run: |
          source venv.pytest/bin/activate && pytest --show-capture=no --alluredir=${GITHUB_WORKSPACE}/allure-results pytest_tests/tests
        working-directory: neofs-testcases

      - name: Publish to NeoFS
        id: put_report
        if: always() && steps.prepare_venv.outcome == 'success'
        uses: nspcc-dev/gh-push-allure-report-to-neofs@v0.1.1
        with:
          NEOFS_WALLET: ${{ secrets.TEST_RESULTS_WALLET }}
          NEOFS_WALLET_PASSWORD: ${{ secrets.TEST_RESULTS_PASSWORD }}
          NEOFS_NETWORK_DOMAIN: ${{ vars.TEST_RESULTS_NEOFS_NETWORK_DOMAIN }}
          NEOFS_HTTP_GATE: ${{ vars.TEST_RESULTS_HTTP_GATE }}
          STORE_OBJECTS_CID: ${{ vars.TEST_RESULTS_CID }}
          PR_LIFETIME: ${{ vars.PR_EXPIRATION_PERIOD }}
          MASTER_LIFETIME: ${{ vars.MASTER_EXPIRATION_PERIOD }}
          MANUAL_RUN_LIFETIME: ${{ vars.MANUAL_RUN_EXPIRATION_PERIOD }}
          OTHER_LIFETIME: ${{ vars.OTHER_EXPIRATION_PERIOD }}
          ALLURE_RESULTS_DIR: ${{ env.ALLURE_RESULTS_DIR }}
          ALLURE_GENERATED_DIR: 'neofs-test-allure-generated-report'

      - name: Post the link to the report
        id: post_report_link
        timeout-minutes: 60
        if: always() && steps.put_report.outcome == 'success'
        env:
          REPORT_NEOFS_URL: ${{ steps.put_report.outputs.REPORT_NEOFS_URL }}index.html
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report ${{ matrix.os.runner }}'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}
          target_url: ${{ env.REPORT_NEOFS_URL }}
